# Generated by Django 2.1.3 on 2018-11-22 19:31

from django.db import migrations, models
import private_files.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, verbose_name='description')),
                ('uploaded_file', private_files.models.fields.PrivateFileField(max_length=600, null=True, upload_to='privado', verbose_name='file')),
            ],
        ),
    ]
