# Generated by Django 2.1.3 on 2018-11-23 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0004_auto_20181122_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='Area_Restringida',
            new_name='area_Restringida',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='Clave',
            new_name='clave',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='Prioridad',
            new_name='prioridad',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='uploaded_file',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
