# Generated by Django 2.1.3 on 2018-11-23 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0006_auto_20181122_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRestringida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_restringida',
        ),
        migrations.RemoveField(
            model_name='area',
            name='password',
        ),
        migrations.AddField(
            model_name='arearestringida',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AreaRestringida', to='archivoDigital.Area'),
        ),
    ]
