# Generated by Django 2.1.3 on 2018-11-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0008_auto_20181122_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_restringida',
            field=models.BooleanField(default=False),
        ),
    ]
