# Generated by Django 2.1.3 on 2018-11-26 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0009_area_area_restringida'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archivoDigital.Area', verbose_name='Área pertenece(n)'),
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_restringido',
            field=models.BooleanField(default=False),
        ),
    ]
