# Generated by Django 2.1.3 on 2018-11-26 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0010_auto_20181125_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRestringido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AreaRestringida', to='archivoDigital.Documento')),
            ],
        ),
    ]
