# Generated by Django 2.1.3 on 2018-11-26 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0011_documentorestringido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorestringido',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentoRestringido', to='archivoDigital.Documento'),
        ),
    ]
