# Generated by Django 2.1.3 on 2018-11-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0012_auto_20181125_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='tipo',
            field=models.CharField(choices=[('Dirección', 'Dirección'), ('Subdirección', 'Subdirección'), ('Coordinación/Jefatura', 'Coordinación/Jefatura')], default='Coordinación/Jefatura', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellidos(s)'),
        ),
    ]
