# Generated by Django 2.1.3 on 2018-11-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0013_auto_20181128_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='clave',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='prioridad',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=1),
        ),
    ]
