# Generated by Django 2.1.3 on 2018-11-29 04:17

from django.db import migrations, models
import django.db.models.deletion
import private_files.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0015_auto_20181128_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivoDigital.Area', verbose_name='Área pertenece(n)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=private_files.models.fields.PrivateFileField(max_length=600, upload_to='privado', verbose_name='file'),
        ),
    ]
