# Generated by Django 2.1.3 on 2018-11-29 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0016_auto_20181128_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archivoDigital.PeriodoGestion', verbose_name='Periodo_Gestión'),
        ),
    ]
