# Generated by Django 2.1.3 on 2018-11-30 05:35

import archivoDigital.models
from django.db import migrations, models
import django.db.models.deletion
import private_files.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0018_ataquemasivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=private_files.models.fields.PrivateFileField(max_length=600, upload_to=archivoDigital.models.defineRuta, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='user',
            name='extension',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Extensión'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Teléfono'),
        ),
    ]
