# Generated by Django 2.1.3 on 2018-12-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0028_auto_20181201_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuntoarea',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
