# Generated by Django 2.1.3 on 2018-12-02 23:55

import archivoDigital.models
from django.db import migrations
import private_files.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0029_auto_20181201_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=private_files.models.fields.PrivateFileField(max_length=1200, upload_to=archivoDigital.models.defineRuta, verbose_name='file'),
        ),
    ]
