# Generated by Django 2.1.3 on 2018-12-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0030_auto_20181202_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=1200, verbose_name='Nombre'),
        ),
    ]
