# Generated by Django 2.1.3 on 2019-04-19 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0033_auto_20181206_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteInsidencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(null=True, verbose_name='hora')),
                ('causa', models.CharField(max_length=150, verbose_name='Causa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='CargaMasiva',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='asuntoarea',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='periodogestion',
            name='periodo',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, unique=True, verbose_name='Año'),
        ),
    ]
